/**
 * The above function is an asynchronous function that returns a list of books of the Bible with their
 * abbreviations, names, and chapter counts.
 * @returns a Response object with the JSON stringified version of the "result" object.
 */
export async function GET() {
  let result = {
    data: [
      {
        id: 1,
        abbr: "Kej",
        name: "Kejadian",
        chapter: 50,
      },
      {
        id: 2,
        abbr: "Kel",
        name: "Keluaran",
        chapter: 40,
      },
      {
        id: 3,
        abbr: "Ima",
        name: "Imamat",
        chapter: 27,
      },
      {
        id: 4,
        abbr: "Bil",
        name: "Bilangan",
        chapter: 36,
      },
      {
        id: 5,
        abbr: "Ula",
        name: "Ulangan",
        chapter: 34,
      },
      {
        id: 6,
        abbr: "Yos",
        name: "Yosua",
        chapter: 24,
      },
      {
        id: 7,
        abbr: "Hak",
        name: "Hakim-hakim",
        chapter: 21,
      },
      {
        id: 8,
        abbr: "Rut",
        name: "Rut",
        chapter: 4,
      },
      {
        id: 9,
        abbr: "1 Sam",
        name: "1 Samuel",
        chapter: 31,
      },
      {
        id: 10,
        abbr: "2 Sam",
        name: "2 Samuel",
        chapter: 24,
      },
      {
        id: 11,
        abbr: "1 Raj",
        name: "1 Raja-Raja",
        chapter: 22,
      },
      {
        id: 12,
        abbr: "2 Raj",
        name: "2 Raja-Raja",
        chapter: 25,
      },
      {
        id: 13,
        abbr: "1 Taw",
        name: "1 Tawarikh",
        chapter: 29,
      },
      {
        id: 14,
        abbr: "2 Taw",
        name: "2 Tawarikh",
        chapter: 36,
      },
      {
        id: 15,
        abbr: "Ezr",
        name: "Ezra",
        chapter: 10,
      },
      {
        id: 16,
        abbr: "Neh",
        name: "Nehemia",
        chapter: 13,
      },
      {
        id: 17,
        abbr: "Est",
        name: "Ester",
        chapter: 10,
      },
      {
        id: 18,
        abbr: "Ayb",
        name: "Ayub",
        chapter: 42,
      },
      {
        id: 19,
        abbr: "Maz",
        name: "Mazmur",
        chapter: 150,
      },
      {
        id: 20,
        abbr: "Ams",
        name: "Amsal",
        chapter: 31,
      },
      {
        id: 21,
        abbr: "Pkh",
        name: "Pengkhotbah",
        chapter: 12,
      },
      {
        id: 22,
        abbr: "Kid",
        name: "Kidung Agung",
        chapter: 8,
      },
      {
        id: 23,
        abbr: "Yes",
        name: "Yesaya",
        chapter: 66,
      },
      {
        id: 24,
        abbr: "Yer",
        name: "Yeremia",
        chapter: 52,
      },
      {
        id: 25,
        abbr: "Rat",
        name: "Ratapan",
        chapter: 5,
      },
      {
        id: 26,
        abbr: "Yeh",
        name: "Yehezkiel",
        chapter: 48,
      },
      {
        id: 27,
        abbr: "Dan",
        name: "Daniel",
        chapter: 12,
      },
      {
        id: 28,
        abbr: "Hos",
        name: "Hosea",
        chapter: 14,
      },
      {
        id: 29,
        abbr: "Yoe",
        name: "Yoel",
        chapter: 3,
      },
      {
        id: 30,
        abbr: "Amo",
        name: "Amos",
        chapter: 9,
      },
      {
        id: 31,
        abbr: "Oba",
        name: "Obaja",
        chapter: 1,
      },
      {
        id: 32,
        abbr: "Yun",
        name: "Yunus",
        chapter: 4,
      },
      {
        id: 33,
        abbr: "Mik",
        name: "Mikha",
        chapter: 7,
      },
      {
        id: 34,
        abbr: "Nah",
        name: "Nahum",
        chapter: 3,
      },
      {
        id: 35,
        abbr: "Hab",
        name: "Habakuk",
        chapter: 3,
      },
      {
        id: 36,
        abbr: "Zef",
        name: "Zefanya",
        chapter: 3,
      },
      {
        id: 37,
        abbr: "Hag",
        name: "Hagai",
        chapter: 2,
      },
      {
        id: 38,
        abbr: "Zak",
        name: "Zakharia",
        chapter: 14,
      },
      {
        id: 39,
        abbr: "Mal",
        name: "Maleakhi",
        chapter: 4,
      },
      {
        id: 40,
        abbr: "Mat",
        name: "Matius",
        chapter: 28,
      },
      {
        id: 41,
        abbr: "Mar",
        name: "Markus",
        chapter: 16,
      },
      {
        id: 42,
        abbr: "Luk",
        name: "Lukas",
        chapter: 24,
      },
      {
        id: 43,
        abbr: "Yoh",
        name: "Yohanes",
        chapter: 21,
      },
      {
        id: 44,
        abbr: "Kis",
        name: "Kisah Para Rasul",
        chapter: 28,
      },
      {
        id: 45,
        abbr: "Rom",
        name: "Roma",
        chapter: 16,
      },
      {
        id: 46,
        abbr: "1 Kor",
        name: "1 Korintus",
        chapter: 16,
      },
      {
        id: 47,
        abbr: "2 Kor",
        name: "2 Korintus",
        chapter: 13,
      },
      {
        id: 48,
        abbr: "Gal",
        name: "Galatia",
        chapter: 6,
      },
      {
        id: 49,
        abbr: "Efe",
        name: "Efesus",
        chapter: 6,
      },
      {
        id: 50,
        abbr: "Flp",
        name: "Filipi",
        chapter: 4,
      },
      {
        id: 51,
        abbr: "Kol",
        name: "Kolose",
        chapter: 4,
      },
      {
        id: 52,
        abbr: "1 Tes",
        name: "1 Tesalonika",
        chapter: 5,
      },
      {
        id: 53,
        abbr: "2 Tes",
        name: "2 Tesalonika",
        chapter: 3,
      },
      {
        id: 54,
        abbr: "1 Tim",
        name: "1 Timotius",
        chapter: 6,
      },
      {
        id: 55,
        abbr: "2 Tim",
        name: "2 Timotius",
        chapter: 4,
      },
      {
        id: 56,
        abbr: "Tit",
        name: "Titus",
        chapter: 3,
      },
      {
        id: 57,
        abbr: "Flm",
        name: "Filemon",
        chapter: 1,
      },
      {
        id: 58,
        abbr: "Ibr",
        name: "Ibrani",
        chapter: 13,
      },
      {
        id: 59,
        abbr: "Yak",
        name: "Yakobus",
        chapter: 5,
      },
      {
        id: 60,
        abbr: "1 Pet",
        name: "1 Petrus",
        chapter: 5,
      },
      {
        id: 61,
        abbr: "2 Pet",
        name: "2 Petrus",
        chapter: 3,
      },
      {
        id: 62,
        abbr: "1 Yoh",
        name: "1 Yohanes",
        chapter: 5,
      },
      {
        id: 63,
        abbr: "2 Yoh",
        name: "2 Yohanes",
        chapter: 1,
      },
      {
        id: 64,
        abbr: "3 Yoh",
        name: "3 Yohanes",
        chapter: 1,
      },
      {
        id: 65,
        abbr: "Yud",
        name: "Yudas",
        chapter: 1,
      },
      {
        id: 66,
        abbr: "Wah",
        name: "Wahyu",
        chapter: 22,
      },
    ],
  };

  return new Response(JSON.stringify(result));
}
